### ISSUE TITLE
install.site and upgrade.site run later

### ISSUE THREAD

**Issue by qbit** [joyent/openbsd-kvm-image-builder#2]
Just a heads up. [This](https://www.openbsd.org/faq/current.html#r20170720) may impact the flow of the image building.

*Edit: Adding the info here as the page will change come 6.2*

---

The execution of the {install,upgrade}.site scripts in bsd.rd was postponed to the end of the installer script. If you use this functionality, make sure your script still works as expected. The script will now run after these steps:
- make underlying device nodes for softraid devices
- install the boot-block on disk
- switch to MP kernel on multi-processor systems
- update kernel.SHA256 and relink kernel
- prepare execution of sysmerge(8) and fw_update(8) on reboot.
- prepare mail with response file to root/admin user

**Comment by chorrell** [comment]
This shouldn't affect the image -- we don't use the the {install,upgrade}.site scripts. I initially used install.site but it wasn't quite working out so I changed to a different approach:

https://github.com/joyent/openbsd-kvm-image-builder/commit/215d10cc97f7ecb91b00c46e5ffdfcf1bb59a475

**Comment by qbit** [comment]
Nice, thanks for the info! Any update on when OpenBSD will be usable via the Joyent stuffs?

**Comment by chorrell** [comment]
Not sure. I work at a different company now. At the time when I finished the image we were waiting for some API changes to land in the Joyent cloud.
